### ISSUE TITLE
Error 400 when sending POST from webhook

### ISSUE THREAD

**Issue by jeremykeen** [InitialState/particle-electron-gps-streamer#3]
Part 4. Using Particles Webhooks says to use "none" for the custom data.  I get error 400 response from InitialState when using this.  Instead, I chose JSON and used this format with success:

{
  "value": "{{PARTICLE_EVENT_VALUE}}",
  "key": "<somekeyname>
}

**Comment by bloukingfisher** [comment]
Solved it for me. I had the same problem with error 400 and Initial State / Particle integration

**Comment by tony1tf** [comment]
I also had Error 400 and couldn't find any information till a Google search brought me here.
JSON format was the key, despite what IS says in their note.

**Comment by davidsulpy** [comment]
Docs updated, thanks!
